controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint","rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint","rear_right_wheel_joint"]
    wheel_separation: 0.35
    wheels_per_side: 2
    wheel_radius: 0.06
    #wheel_separation_multiplier: 1.0
    #left_wheel_radius_multiplier: 1.0
    #right_wheel_radius_multiplier: 1.0
    
    publish_rate: 20.0
    publish_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
    odom_topic: /odom
    cmd_vel_topic: /cmd_vel
    
    cmd_vel_timeout: 1.0
    use_stamped_vel: false
    
    
    
    # Velocity and acceleration limits
    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    
    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
